const fs = require('fs');
const code = [
'"use client"',
'import { useState } from "react"',
'import { useRouter } from "next/navigation"',
'import { useSession } from "next-auth/react"',
'import Navbar from "@/components/Navbar"',
'',
'const WASTE_TYPES = [',
'  { id: "plastik",    label: "Plastik",    poin: 500,  desc: "Botol, kantong, wadah" },',
'  { id: "kertas",     label: "Kertas",     poin: 300,  desc: "Koran, kardus, buku" },',
'  { id: "logam",      label: "Logam",      poin: 800,  desc: "Kaleng, besi, tembaga" },',
'  { id: "kaca",       label: "Kaca",       poin: 400,  desc: "Botol kaca, cermin" },',
'  { id: "elektronik", label: "Elektronik", poin: 1000, desc: "HP, kabel, baterai" },',
']',
'',
'export default function NewRequestPage() {',
'  const { data: session } = useSession()',
'  const router = useRouter()',
'  const [selectedTypes, setSelectedTypes] = useState([])',
'  const [form, setForm] = useState({ estimatedWeight: "", addressDetail: "", notes: "" })',
'  const [loading, setLoading] = useState(false)',
'  const [error, setError] = useState("")',
'',
'  function toggleType(id) {',
'    setSelectedTypes(prev => prev.includes(id) ? prev.filter(t => t !== id) : [...prev, id])',
'  }',
'',
'  async function handleSubmit(e) {',
'    e.preventDefault()',
'    if (selectedTypes.length === 0) { setError("Pilih minimal satu jenis sampah"); return }',
'    setLoading(true)',
'    setError("")',
'    const res = await fetch("/api/requests", {',
'      method: "POST",',
'      headers: { "Content-Type": "application/json" },',
'      body: JSON.stringify({',
'        sampahTypes: JSON.stringify(selectedTypes),',
'        estimatedWeight: parseFloat(form.estimatedWeight) || null,',
'        addressDetail: form.addressDetail,',
'        notes: form.notes,',
'      }),',
'    })',
'    const data = await res.json()',
'    if (!res.ok) { setError(data.error || "Terjadi kesalahan"); setLoading(false); return }',
'    router.push("/household")',
'  }',
'',
'  const estPoints = selectedTypes.reduce((sum, t) => {',
'    const found = WASTE_TYPES.find(w => w.id === t)',
'    return sum + (found ? found.poin : 0)',
'  }, 0) * (parseFloat(form.estimatedWeight) || 1)',
'',
'  return (',
'    <div style={{minHeight:"100vh",background:"#f8fafc"}}>',
'      <Navbar userName={session?.user?.name || ""} role="HOUSEHOLD" />',
'      <div style={{maxWidth:"680px",margin:"0 auto",padding:"24px"}}>',
'        <div style={{display:"flex",alignItems:"center",gap:"12px",marginBottom:"20px"}}>',
'          <button onClick={() => router.back()} style={{fontSize:"13px",color:"#64748b",background:"none",border:"none",cursor:"pointer"}}>Kembali</button>',
'          <div>',
'            <h1 style={{fontSize:"20px",fontWeight:"700",color:"#0f172a"}}>Buat Request Sampah</h1>',
'            <p style={{fontSize:"12px",color:"#94a3b8"}}>Isi detail sampah yang ingin dijemput</p>',
'          </div>',
'        </div>',
'',
'        {error && <div style={{fontSize:"13px",padding:"12px",borderRadius:"8px",background:"#fef2f2",color:"#dc2626",marginBottom:"16px",border:"1px solid #fecaca"}}>{error}</div>}',
'',
'        <div style={{background:"#fff",borderRadius:"12px",padding:"20px",border:"1px solid #e2e8f0",marginBottom:"16px"}}>',
'          <h2 style={{fontSize:"14px",fontWeight:"700",color:"#0f172a",marginBottom:"12px"}}>Jenis Sampah</h2>',
'          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"8px"}}>',
'            {WASTE_TYPES.map(type => (',
'              <button key={type.id} type="button" onClick={() => toggleType(type.id)}',
'                style={{padding:"14px",borderRadius:"10px",border: selectedTypes.includes(type.id) ? "2px solid #16a34a" : "2px solid #e2e8f0",background: selectedTypes.includes(type.id) ? "#f0fdf4" : "#fff",textAlign:"left",cursor:"pointer",transition:"all 0.15s"}}>',
'                <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:"4px"}}>',
'                  <span style={{fontSize:"13px",fontWeight:"600",color:"#1e293b"}}>{type.label}</span>',
'                  {selectedTypes.includes(type.id) && <span style={{color:"#16a34a",fontWeight:"700"}}>v</span>}',
'                </div>',
'                <p style={{fontSize:"11px",color:"#94a3b8",marginBottom:"4px"}}>{type.desc}</p>',
'                <p style={{fontSize:"11px",fontWeight:"600",color:"#16a34a"}}>{type.poin.toLocaleString()} poin/kg</p>',
'              </button>',
'            ))}',
'          </div>',
'        </div>',
'',
'        <div style={{background:"#fff",borderRadius:"12px",padding:"20px",border:"1px solid #e2e8f0",marginBottom:"16px"}}>',
'          <h2 style={{fontSize:"14px",fontWeight:"700",color:"#0f172a",marginBottom:"16px"}}>Detail Penjemputan</h2>',
'          <div style={{marginBottom:"14px"}}>',
'            <label style={{display:"block",fontSize:"13px",fontWeight:"500",color:"#374151",marginBottom:"6px"}}>Estimasi Berat (kg)</label>',
'            <input type="number" step="0.1" min="0.1" value={form.estimatedWeight}',
'              onChange={e => setForm({...form, estimatedWeight: e.target.value})}',
'              style={{width:"100%",padding:"10px 14px",borderRadius:"8px",border:"1px solid #d1d5db",fontSize:"13px",outline:"none",boxSizing:"border-box"}}',
'              placeholder="Contoh: 2.5" />',
'          </div>',
'          <div style={{marginBottom:"14px"}}>',
'            <label style={{display:"block",fontSize:"13px",fontWeight:"500",color:"#374151",marginBottom:"6px"}}>Alamat Penjemputan</label>',
'            <textarea value={form.addressDetail}',
'              onChange={e => setForm({...form, addressDetail: e.target.value})}',
'              style={{width:"100%",padding:"10px 14px",borderRadius:"8px",border:"1px solid #d1d5db",fontSize:"13px",outline:"none",boxSizing:"border-box",resize:"vertical"}}',
'              placeholder="Contoh: Jl. Merdeka No. 10, RT 03/RW 05" rows={3} required />',
'          </div>',
'          <div>',
'            <label style={{display:"block",fontSize:"13px",fontWeight:"500",color:"#374151",marginBottom:"6px"}}>Catatan (opsional)</label>',
'            <textarea value={form.notes}',
'              onChange={e => setForm({...form, notes: e.target.value})}',
'              style={{width:"100%",padding:"10px 14px",borderRadius:"8px",border:"1px solid #d1d5db",fontSize:"13px",outline:"none",boxSizing:"border-box",resize:"vertical"}}',
'              placeholder="Contoh: Sampah ada di depan pagar" rows={2} />',
'          </div>',
'        </div>',
'',
'        {selectedTypes.length > 0 && form.estimatedWeight && (',
'          <div style={{borderRadius:"12px",padding:"16px 20px",display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"16px",background:"#f0fdf4",border:"1px solid #bbf7d0"}}>',
'            <div>',
'              <p style={{fontSize:"12px",fontWeight:"700",color:"#16a34a",marginBottom:"4px"}}>Estimasi poin yang kamu dapatkan</p>',
'              <p style={{fontSize:"24px",fontWeight:"700",color:"#14532d"}}>{Math.round(estPoints).toLocaleString("id-ID")} poin</p>',
'            </div>',
'            <div style={{fontSize:"32px"}}>Koin</div>',
'          </div>',
'        )}',
'',
'        <button onClick={handleSubmit} disabled={loading}',
'          style={{width:"100%",padding:"14px",borderRadius:"10px",border:"none",background: loading ? "#94a3b8" : "#16a34a",color:"#fff",fontSize:"14px",fontWeight:"600",cursor: loading ? "not-allowed" : "pointer"}}>',
'          {loading ? "Mengirim request..." : "Kirim Request"}',
'        </button>',
'      </div>',
'    </div>',
'  )',
'}',
].join('\n');
fs.writeFileSync('app/(dashboard)/household/request/new/page.tsx', code, {encoding:'utf8'});
console.log('new-request OK');
