const fs = require('fs');
const c = [
'"use client"',
'import { useSession } from "next-auth/react"',
'import { useRouter } from "next/navigation"',
'import { useEffect, useState } from "react"',
'import Navbar from "@/components/Navbar"',
'function PickupCard({ req, onComplete }) {',
'  const [weight, setWeight] = useState("")',
'  const types = JSON.parse(req.sampahTypes || "[]")',
'  return (',
'    <div className="p-4 rounded-lg border border-gray-100">',
'      <div className="flex gap-1.5 flex-wrap mb-2">',
'        {types.map((t) => <span key={t} className="text-xs px-2 py-0.5 rounded-full bg-green-100 text-green-800 capitalize">{t}</span>)}',
'      </div>',
'      <p className="text-sm font-medium text-gray-800 mb-0.5">{req.addressDetail}</p>',
'      <p className="text-xs text-gray-400 mb-3">Dari: {req.householdName}</p>',
'      {req.status !== "COMPLETED" ? (',
'        <div className="flex gap-2">',
'          <input type="number" placeholder="Berat aktual (kg)" value={weight} onChange={e => setWeight(e.target.value)} className="flex-1 px-3 py-2 rounded-lg border border-gray-200 text-sm" />',
'          <button onClick={() => onComplete(req.id, weight)} disabled={!weight} className="px-4 py-2 rounded-lg text-sm font-semibold text-white disabled:opacity-40" style={{background:"#16a34a"}}>Selesaikan</button>',
'        </div>',
'      ) : (',
'        <span className="text-xs px-2.5 py-1 rounded-full bg-green-100 text-green-800">Selesai - {req.actualWeight} kg</span>',
'      )}',
'    </div>',
'  )',
'}',
'export default function CollectorDashboard() {',
'  const { data: session, status } = useSession()',
'  const router = useRouter()',
'  const [requests, setRequests] = useState([])',
'  const [myPickups, setMyPickups] = useState([])',
'  const [loading, setLoading] = useState(true)',
'  const [tab, setTab] = useState("available")',
'  useEffect(() => { if (status === "unauthenticated") router.push("/login") }, [status, router])',
'  useEffect(() => { if (status === "authenticated") fetchData() }, [status])',
'  async function fetchData() {',
'    setLoading(true)',
'    const [a, m] = await Promise.all([',
'      fetch("/api/requests/available").then(r => r.json()),',
'      fetch("/api/requests/my-pickups").then(r => r.json()),',
'    ])',
'    setRequests(a.requests || [])',
'    setMyPickups(m.requests || [])',
'    setLoading(false)',
'  }',
'  async function acceptRequest(id) {',
'    const res = await fetch("/api/requests/" + id + "/accept", { method: "POST" })',
'    if (res.ok) fetchData()',
'  }',
'  async function completeRequest(id, weight) {',
'    if (!weight) return',
'    const res = await fetch("/api/requests/" + id + "/complete", {',
'      method: "POST", headers: { "Content-Type": "application/json" },',
'      body: JSON.stringify({ actualWeight: parseFloat(weight) }),',
'    })',
'    if (res.ok) { const d = await res.json(); alert("Selesai! Household mendapat " + d.pointsEarned + " poin"); fetchData() }',
'  }',
'  if (status === "loading") return <div className="min-h-screen flex items-center justify-center">Memuat...</div>',
'  return (',
'    <div className="min-h-screen bg-gray-50">',
'      <Navbar userName={session?.user?.name || ""} role="COLLECTOR" />',
'      <div className="max-w-4xl mx-auto px-6 py-8">',
'        <div className="mb-6"><h1 className="text-xl font-bold text-gray-900">Dashboard Pengepul</h1><p className="text-sm text-gray-500">Ambil request sampah dan kelola pickup kamu</p></div>',
'        <div className="grid grid-cols-2 gap-4 mb-6">',
'          <div className="bg-white rounded-xl p-5 border border-gray-100"><div className="text-2xl font-bold mb-1" style={{color:"#16a34a"}}>{requests.length}</div><div className="text-xs text-gray-500">Request Tersedia</div></div>',
'          <div className="bg-white rounded-xl p-5 border border-gray-100"><div className="text-2xl font-bold mb-1" style={{color:"#d97706"}}>{myPickups.filter(r => r.status !== "COMPLETED").length}</div><div className="text-xs text-gray-500">Sedang Diproses</div></div>',
'        </div>',
'        <div className="flex gap-2 mb-4">',
'          <button onClick={() => setTab("available")} className="px-4 py-2 text-sm font-medium rounded-lg border" style={tab==="available" ? {background:"#f0fdf4",color:"#16a34a",borderColor:"#16a34a"} : {background:"#fff",color:"#6b7280",borderColor:"#e5e7eb"}}>Request Tersedia ({requests.length})</button>',
'          <button onClick={() => setTab("mypickups")} className="px-4 py-2 text-sm font-medium rounded-lg border" style={tab==="mypickups" ? {background:"#f0fdf4",color:"#16a34a",borderColor:"#16a34a"} : {background:"#fff",color:"#6b7280",borderColor:"#e5e7eb"}}>Pickup Saya ({myPickups.length})</button>',
'          <button onClick={() => router.push("/collector/batch/new")} className="ml-auto text-xs font-semibold px-3 py-2 rounded-lg text-white" style={{background:"#16a34a"}}>+ Listing Batch</button>',
'        </div>',
'        <div className="bg-white rounded-xl border border-gray-100 p-4">',
'          {loading ? (<div className="text-center py-10 text-sm text-gray-400">Memuat data...</div>)',
'          : tab === "available" ? (',
'            requests.length === 0 ? (<div className="text-center py-14"><p className="text-sm text-gray-500">Tidak ada request tersedia</p></div>)',
'            : <div className="space-y-2">{requests.map((req) => { const types = JSON.parse(req.sampahTypes || "[]"); return (',
'                <div key={req.id} className="flex justify-between items-start p-4 rounded-lg border border-gray-100">',
'                  <div>',
'                    <div className="flex gap-1.5 mb-1.5">{types.map((t) => <span key={t} className="text-xs px-2 py-0.5 rounded-full bg-green-100 text-green-800 capitalize">{t}</span>)}</div>',
'                    <p className="text-sm font-medium text-gray-800">{req.addressDetail}</p>',
'                    <p className="text-xs text-gray-400">Dari: {req.householdName}{req.estimatedWeight ? " - Est. " + req.estimatedWeight + " kg" : ""}</p>',
'                  </div>',
'                  <button onClick={() => acceptRequest(req.id)} className="text-sm font-semibold text-white px-4 py-2 rounded-lg ml-4" style={{background:"#16a34a"}}>Ambil</button>',
'                </div>',
'              )})}</div>',
'          ) : (',
'            myPickups.length === 0 ? (<div className="text-center py-14"><p className="text-sm text-gray-500">Belum ada pickup</p></div>)',
'            : <div className="space-y-2">{myPickups.map((req) => <PickupCard key={req.id} req={req} onComplete={completeRequest} />)}</div>',
'          )}',
'        </div>',
'      </div>',
'    </div>',
'  )',
'}',
].join('\n');
fs.writeFileSync('app/(dashboard)/collector/page.tsx', c, {encoding:'utf8'});
console.log('collector OK');
